//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Data.EntityClient;
using System.ComponentModel;
using System.Xml.Serialization;
using System.Runtime.Serialization;

[assembly: EdmSchemaAttribute()]

namespace BetEx247.Data.Model
{
    #region Contexts
    
    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class BetEXDataContainer : ObjectContext
    {
        #region Constructors
    
        /// <summary>
        /// Initializes a new BetEXDataContainer object using the connection string found in the 'BetEXDataContainer' section of the application configuration file.
        /// </summary>
        public BetEXDataContainer() : base("name=BetEXDataContainer", "BetEXDataContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BetEXDataContainer object.
        /// </summary>
        public BetEXDataContainer(string connectionString) : base(connectionString, "BetEXDataContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Initialize a new BetEXDataContainer object.
        /// </summary>
        public BetEXDataContainer(EntityConnection connection) : base(connection, "BetEXDataContainer")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Partial Methods
    
        partial void OnContextCreated();
    
        #endregion
    
    }
    

    #endregion
    
    
}
